version: '3.9'

services:
  bot:
    build: .
    env_file:
    - .env
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DiSCORD_BOT_OWNER_ID: ${DiSCORD_BOT_OWNER_ID}
      DISCORD_ERROR_CHANNEL_ID: ${DISCORD_ERROR_CHANNEL_ID}
      DISCORD_ERROR_ROLE_ID: ${DISCORD_ERROR_ROLE_ID}
      DEEPL_KEY: "${DEEPL_KEY}"
      HOLODEX_API_KEY: "${HOLODEX_API_KEY}"
      MONGODB_URL: "${MONGODB_URL}"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mongo:4.4.18
    volumes:
      - ./data/mongo:/data/db
    restart: unless-stopped
