export const idol = [
  {
    name: 'Rin Penrose',
    ytId: 'UCpZIbzoEC_3rZglErpQkbDg',
    chName: 'Rin Penrose Ch. idol-EN',
    picture: '',
    groups: ['idol-EN'],
    twitter: 'RinPenrose',
    aliases: [],
  },
  {
    name: 'Riro Ron',
    ytId: 'UCGaN6JMiDHZSkPXt-82b6yQ',
    chName: 'Riro Ron Ch. idol-EN',
    picture: '',
    groups: ['idol-EN'],
    twitter: 'RiroRonSTAR',
    aliases: [],
  },
  {
    name: 'Roca Rourin',
    ytId: 'UC9xR7uN0x5a6CH3Uopq7czA',
    chName: 'Roca Rourin Ch. idol-EN',
    picture: '',
    groups: ['idol-EN'],
    twitter: 'RocaRourin',
    aliases: [],
  },
  {
    name: 'Poko Rakun',
    ytId: 'UCk2k1y-d24nFyVCvyxnAaYA',
    chName: 'Poko Rakun Ch. idol-EN',
    picture: '',
    groups: ['idol-EN'],
    twitter: 'PokoRakun',
    aliases: [],
  },
  {
    name: 'Kai Saikota',
    ytId: 'UCk2k1y-d24nFyVCvyxnAaYA',
    chName: 'Kai Saikota Ch. idol-EN',
    picture: '',
    groups: ['idol-EN'],
    twitter: 'KaiSaikota',
    aliases: [],
  },
  {
    name: 'Momo Otako',
    ytId: 'UCe0JiGnjPfEwEIbWASbOimw',
    chName: 'Momo Otako Ch. idol-EN',
    picture: '',
    groups: ['idol-EN'],
    twitter: 'MomoOtako',
    aliases: [],
  },
  {
    name: 'Coni Confetti',
    ytId: 'UCUfgKgCxtFs1ZPlyiM3JcTw',
    chName: 'Coni Confetti Ch. idol-EN',
    picture: '',
    groups: ['idol-EN'],
    twitter: 'coni_confetti',
    aliases: [],
  },
  {
    name: 'Yuko Yurei',
    ytId: 'UCcIcMRVpNqWQn4WnDhRASAw',
    chName: 'Yuko Yurei Ch. idol-EN',
    picture: '',
    groups: ['idol-EN'],
    twitter: 'YureiYuko',
    aliases: [],
  },
  {
    name: 'Juna Unagi',
    ytId: 'UCTFCSCPvqjXEs3zq91aeOVg',
    chName: 'Juna Unagi Ch. idol-EN',
    picture: '',
    groups: ['idol-EN'],
    twitter: 'JunaUnagi',
    aliases: [],
  },
  {
    name: 'Pochi Wanmaru',
    ytId: 'UCP0csSl19lOSNwJGCFsJqAQ',
    chName: 'Pochi Wanmaru Ch. idol-EN',
    picture: '',
    groups: ['idol-EN'],
    twitter: 'pochiwanmaru',
    aliases: [],
  },
  {
    name: 'Fuyo Cloverfield',
    ytId: 'UC8zgKaS8LiyL28mdhRC2nBg',
    chName: 'Fuyo Cloverfield Ch. idol-EN',
    picture: '',
    groups: ['idol-EN'],
    twitter: 'FuyoCloverfield',
    aliases: [],
  },
] as const
