export const idol = [
  {
    name: 'Rin Penrose',
    ytId: 'UCpZIbzoEC_3rZglErpQkbDg',
    chName: 'Rin Penrose Ch. idol-EN',
    picture: '',
    groups: ['idol-EN'],
    twitter: 'RinPenrose',
    aliases: [],
  },
  {
    name: 'Roca Rourin',
    ytId: 'UC9xR7uN0x5a6CH3Uopq7czA',
    chName: 'Roca Rourin Ch. idol-EN',
    picture: '',
    groups: ['idol-EN'],
    twitter: 'RocaRourin',
    aliases: [],
  },
  {
    name: 'Poko Rakun',
    ytId: 'UCk2k1y-d24nFyVCvyxnAaYA',
    chName: 'Poko Rakun Ch. idol-EN',
    picture: '',
    groups: ['idol-EN'],
    twitter: 'PokoRakun',
    aliases: [],
  },
  {
    name: 'Juna Unagi',
    ytId: 'UCTFCSCPvqjXEs3zq91aeOVg',
    chName: 'Juna Unagi Ch. idol-EN',
    picture: '',
    groups: ['idol-EN'],
    twitter: 'JunaUnagi',
    aliases: [],
  },
  {
    name: 'Fuyo Cloverfield',
    ytId: 'UC8zgKaS8LiyL28mdhRC2nBg',
    chName: 'Fuyo Cloverfield Ch. idol-EN',
    picture: '',
    groups: ['idol-EN'],
    twitter: 'FuyoCloverfield',
    aliases: [],
  },
] as const
